# Generated by Django 5.1.4 on 2025-06-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('system_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('cohere', 'Cohere'), ('anthropic', 'Anthropic'), ('huggingface', 'HuggingFace'), ('azure_openai', 'Azure OpenAI'), ('google', 'Google PaLM/Gemini')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=20)),
                ('top_p', models.FloatField(default=1.0, help_text='Nucleus sampling parameter')),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific settings')),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority models are tried first')),
                ('description', models.TextField(blank=True)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='LLMChat.conversation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LLMChat.modelprovider')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
